#!/usr/bin/env bash
#MISE description="Render an image's committed definition from its template + blocks"
#USAGE arg "<image>" help="Image dir under images/ (e.g. coder-base)"
set -eo pipefail

# shellcheck disable=SC2154  # usage_image from #USAGE
img="${usage_image:?}"
dir="images/$img"
[ -f "$dir/manifest.yaml.tpl" ] || { echo "no $dir/manifest.yaml.tpl" >&2; exit 1; }

{
  printf '%s\n' '---'
  printf '# Generated by: mise run render %s — DO NOT EDIT.\n' "$img"
  ( cd "$dir" && gomplate --left-delim '[[' --right-delim ']]' -f manifest.yaml.tpl )
} | sed 's/[[:space:]]*$//' > "$dir/$img.yaml"
